# Generated by Django 2.1.5 on 2019-11-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191128_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='heading',
            field=models.CharField(blank=True, help_text='This is not a must', max_length=50, null=True),
        ),
    ]
