# Generated by Django 2.1.5 on 2019-11-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20191128_2153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.BooleanField(default=False, help_text='IF NOT PUBLISHED IT WILL NOT APPEAR ANYWHERE'),
        ),
    ]
