# Generated by Django 2.1.5 on 2019-10-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EagleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('PT', 'Portrait'), ('CV', 'cover'), ('BD', 'background'), ('PF', 'portfolio'), ('FY', 'family')], default='PT', max_length=2)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.ImageField(upload_to='eagle-images/')),
            ],
        ),
    ]
