# Generated by Django 2.1.5 on 2019-10-31 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EagleImage',
        ),
    ]
