# Generated by Django 2.1.5 on 2019-10-31 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wing', '0002_delete_eagleimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('portfolio_type', models.CharField(max_length=3)),
                ('image', models.ImageField(upload_to='portfolio/portfolio_images/')),
                ('description', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
    ]
