# Generated by Django 2.1.5 on 2019-11-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wing', '0006_usermessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EagleExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(help_text='Where did you work?', max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('started', models.DateField()),
                ('ended', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
