# Generated by Django 2.1.5 on 2019-11-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wing', '0007_eagleexperience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(help_text='What institution were you in?', max_length=50)),
                ('qualification', models.CharField(help_text='What did you achieve?', max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('started', models.DateField()),
                ('ended', models.DateField(blank=True, help_text='If you leave this blank it will indicate that you are a continuing student')),
            ],
        ),
        migrations.AlterField(
            model_name='eagleexperience',
            name='ended',
            field=models.DateField(blank=True, help_text='If you leave this blank it will indicate that you still work here', null=True),
        ),
    ]
