# Generated by Django 2.1.5 on 2019-11-29 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wing', '0008_auto_20191129_1406'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Education',
            new_name='EagleEducation',
        ),
    ]
