# Generated by Django 2.1.5 on 2019-11-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wing', '0009_auto_20191129_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eagleeducation',
            options={'verbose_name': 'Eagle education experience', 'verbose_name_plural': 'Eagle education experiences'},
        ),
        migrations.AlterField(
            model_name='eagleeducation',
            name='ended',
            field=models.DateField(blank=True, help_text='If you leave this blank it will indicate that you are a continuing student', null=True),
        ),
    ]
