# Generated by Django 2.1.5 on 2019-11-29 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wing', '0010_auto_20191129_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eagleeducation',
            options={'ordering': ('-started',), 'verbose_name': 'Eagle education experience', 'verbose_name_plural': 'Eagle education experiences'},
        ),
        migrations.AlterModelOptions(
            name='eagleexperience',
            options={'ordering': ('-started',)},
        ),
    ]
