# Generated by Django 2.1.5 on 2020-05-31 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wing', '0011_auto_20191129_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='EagleProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('portrait', models.ImageField(upload_to='eagle_details/')),
                ('github', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Super Details',
                'verbose_name_plural': 'Eagle Details',
            },
        ),
        migrations.DeleteModel(
            name='EagleDetails',
        ),
    ]
