# Generated by Django 2.1.5 on 2020-05-31 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wing', '0012_auto_20200531_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eagleprofile',
            options={'verbose_name': 'Super Profile', 'verbose_name_plural': 'Eagle Profile'},
        ),
        migrations.AddField(
            model_name='eagleprofile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
